name: DeveloperNotes
version: '${project.version}'
main: adhdmc.developernotes.DeveloperNotes
api-version: 1.19
authors: [ Rhythmic, Peashooter101 ]
description: Used for developer notes for general practices we may use across different projects.
